import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";



const outfit = Outfit({
  
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.className} `}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/*header*/}
            <main className="min-h-screen bg-background">
            {children}
            </main>
            {/*footer*/}
            
              <footer className="bg-muted/50 py-12">
              <div className="container mx-auto text-center text-gray-200" >
                <p>Made by Subhrodeep</p>
              </div>
              </footer>
        
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
